# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Media Theory—Media Practice
tagline:             'ENG 7006, Winter 2015'
description:         'Media Theory—Media Practice course taught by Scott Richmond in Winter 2015 at Wayne State: media theory and coding.'
url:                 http://eng7006.github.io
baseurl:             ''
paginate:            7

# About/contact
author:
  name:              Scott C. Richmond
  url:               https://kredati.org
  email:             scr@wayne.edu

# Custom vars
version:             1.0.0

# Jekyll-paginate?
gems: [Jekyll-paginate]
